sensor:
# ZeverSolar Inverter Local Data Sensors
  - platform: rest
    name: Solar Error #0 When No Error
    resource: http://192.168.1.167/home.cgi
    value_template: "{{ value.split()[8].split()[0] }}" 
  - platform: rest
    name: Solar Pac
    unit_of_measurement: W
    resource: http://192.168.1.167/home.cgi
    value_template: "{{ value.split()[11].split()[0] }}"
  - platform: rest
    name: Solar E_Today
    unit_of_measurement: KWh  
    resource: http://192.168.1.167/home.cgi
    value_template: "{{ value.split()[12].split()[0] }}"
  - platform: rest
    name: Solar Status #OK When No Error
    resource: http://192.168.1.167/home.cgi
    value_template: "{{ value.split()[13].split()[0] }}" 
